name: mockmate
description: MockMate interview practice app
publish_to: "none"

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  camera: ^0.11.0+2
  google_mlkit_face_detection: ^0.11.0
  video_player: ^2.9.2
  path_provider: ^2.1.4
  shared_preferences: ^2.3.2

flutter:
  uses-material-design: true
